-- ─── Consultoria Public Flow + Proposals ─────────────────────────────────────
-- Fluxo público: briefing sem auth → guided chat → diagnóstico Claude → proposta

-- 1. Extend consultoria_sessions for public (tokenized) sessions
ALTER TABLE consultoria_sessions
  ALTER COLUMN client_id DROP NOT NULL;

ALTER TABLE consultoria_sessions
  ADD COLUMN IF NOT EXISTS lead_id          uuid REFERENCES public.leads(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS session_token    text UNIQUE,
  ADD COLUMN IF NOT EXISTS flow_step        text NOT NULL DEFAULT 'briefing'
    CHECK (flow_step IN ('briefing','guided_chat','live_call','diagnosis','proposal','delivered')),
  ADD COLUMN IF NOT EXISTS briefing_data    jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS chat_turn_count  integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS diagnosis_status text NOT NULL DEFAULT 'pending'
    CHECK (diagnosis_status IN ('pending','generating','done','failed')),
  ADD COLUMN IF NOT EXISTS voice_transcript text,
  ADD COLUMN IF NOT EXISTS updated_at       timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_consultoria_sessions_lead_id      ON consultoria_sessions(lead_id);
CREATE INDEX IF NOT EXISTS idx_consultoria_sessions_token        ON consultoria_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_consultoria_sessions_flow_step    ON consultoria_sessions(flow_step);
CREATE INDEX IF NOT EXISTS idx_consultoria_sessions_diag_status  ON consultoria_sessions(diagnosis_status);

-- 2. Extend leads with briefing fields
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS company_name       text,
  ADD COLUMN IF NOT EXISTS main_challenge     text,
  ADD COLUMN IF NOT EXISTS already_tried      text,
  ADD COLUMN IF NOT EXISTS diagnosis_sent_at  timestamptz,
  ADD COLUMN IF NOT EXISTS proposal_sent_at   timestamptz;

-- 3. Proposals table — generated by Claude, approved by ATom's team
CREATE TABLE IF NOT EXISTS public.proposals (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id        uuid NOT NULL REFERENCES consultoria_sessions(id) ON DELETE CASCADE,
  lead_id           uuid NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,

  -- Generated by Claude
  summary           text NOT NULL,           -- 2-3 linhas do diagnóstico resumido
  scope_items       jsonb NOT NULL DEFAULT '[]'::jsonb, -- [{title, description, hours?}]
  investment_min    integer,                 -- valor mínimo em centavos
  investment_max    integer,                 -- valor máximo em centavos
  investment_label  text,                    -- ex: "R$ 4.800 – R$ 7.200"
  timeline_weeks    integer,                 -- prazo em semanas
  timeline_label    text,                    -- ex: "6–8 semanas"
  differentials     jsonb DEFAULT '[]'::jsonb, -- bullets de diferencial ATom's
  next_steps        jsonb DEFAULT '[]'::jsonb, -- o que acontece após o aceite

  -- ATom's approval workflow
  status            text NOT NULL DEFAULT 'pending_approval'
    CHECK (status IN ('pending_approval','approved','rejected','sent','accepted','declined')),
  approved_by       text,                    -- email do membro da equipe
  approved_at       timestamptz,
  rejection_reason  text,
  edited_summary    text,                    -- versão editada pela equipe (opcional)
  edited_investment_label text,
  edited_timeline_label   text,

  -- Delivery
  pdf_url           text,                    -- URL do PDF gerado
  sent_at           timestamptz,
  client_accepted_at timestamptz,
  client_declined_at timestamptz,
  client_notes      text,                    -- comentário do cliente ao aceitar/recusar

  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_proposals_session_id ON proposals(session_id);
CREATE INDEX IF NOT EXISTS idx_proposals_lead_id    ON proposals(lead_id);
CREATE INDEX IF NOT EXISTS idx_proposals_status     ON proposals(status);

-- 4. RLS for proposals
ALTER TABLE public.proposals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_all_proposals" ON public.proposals;
CREATE POLICY "admin_all_proposals" ON public.proposals
  FOR ALL TO authenticated USING (true);

-- 5. RLS for consultoria_sessions — allow service role and authenticated (admin)
DROP POLICY IF EXISTS "admin_all_sessions" ON consultoria_sessions;
CREATE POLICY "admin_all_sessions" ON consultoria_sessions
  FOR ALL TO authenticated USING (true);

-- 6. Trigger to keep updated_at fresh on proposals
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $BODY$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$BODY$;

DROP TRIGGER IF EXISTS proposals_updated_at ON public.proposals;
CREATE TRIGGER proposals_updated_at
  BEFORE UPDATE ON public.proposals
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS sessions_updated_at ON public.consultoria_sessions;
CREATE TRIGGER sessions_updated_at
  BEFORE UPDATE ON public.consultoria_sessions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
